# Generated by Django 4.0.5 on 2022-07-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
